/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_LBRACE_LBRACE = 3,
  anon_sym_DOT = 4,
  anon_sym_RBRACE_RBRACE = 5,
  anon_sym_DOLLAR_LBRACE = 6,
  anon_sym_AT = 7,
  anon_sym_DOLLAR = 8,
  sym_identifier = 9,
  sym_numeric_index = 10,
  anon_sym_COLON = 11,
  aux_sym_format_spec_token1 = 12,
  sym_literal_text = 13,
  sym_template = 14,
  sym__template_content = 15,
  sym_property = 16,
  sym_go_property = 17,
  sym_builtin_property = 18,
  sym_hint_symbol = 19,
  sym__property_name = 20,
  sym_dotted_name = 21,
  sym_format_spec = 22,
  aux_sym_template_repeat1 = 23,
  aux_sym_dotted_name_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_DOT] = ".",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [anon_sym_AT] = "@",
  [anon_sym_DOLLAR] = "$",
  [sym_identifier] = "identifier",
  [sym_numeric_index] = "numeric_index",
  [anon_sym_COLON] = ":",
  [aux_sym_format_spec_token1] = "identifier",
  [sym_literal_text] = "literal_text",
  [sym_template] = "template",
  [sym__template_content] = "_template_content",
  [sym_property] = "property",
  [sym_go_property] = "go_property",
  [sym_builtin_property] = "builtin_property",
  [sym_hint_symbol] = "hint_symbol",
  [sym__property_name] = "_property_name",
  [sym_dotted_name] = "dotted_name",
  [sym_format_spec] = "format_spec",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_dotted_name_repeat1] = "dotted_name_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_identifier] = sym_identifier,
  [sym_numeric_index] = sym_numeric_index,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_format_spec_token1] = sym_identifier,
  [sym_literal_text] = sym_literal_text,
  [sym_template] = sym_template,
  [sym__template_content] = sym__template_content,
  [sym_property] = sym_property,
  [sym_go_property] = sym_go_property,
  [sym_builtin_property] = sym_builtin_property,
  [sym_hint_symbol] = sym_hint_symbol,
  [sym__property_name] = sym__property_name,
  [sym_dotted_name] = sym_dotted_name,
  [sym_format_spec] = sym_format_spec,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_dotted_name_repeat1] = aux_sym_dotted_name_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_numeric_index] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_format_spec_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_text] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__template_content] = {
    .visible = false,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_go_property] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin_property] = {
    .visible = true,
    .named = true,
  },
  [sym_hint_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym__property_name] = {
    .visible = false,
    .named = true,
  },
  [sym_dotted_name] = {
    .visible = true,
    .named = true,
  },
  [sym_format_spec] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_name_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_format = 1,
  field_format_string = 2,
  field_hint = 3,
  field_name = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_format] = "format",
  [field_format_string] = "format_string",
  [field_hint] = "hint",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_format_string, 1},
  [1] =
    {field_hint, 1},
  [2] =
    {field_name, 1},
  [3] =
    {field_format, 1},
  [4] =
    {field_hint, 1},
    {field_name, 2},
  [6] =
    {field_format, 2},
    {field_hint, 1},
  [8] =
    {field_format, 2},
    {field_name, 1},
  [10] =
    {field_name, 2},
  [11] =
    {field_format, 3},
    {field_hint, 1},
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(8);
      if (lookahead == '$') ADVANCE(21);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '@') ADVANCE(19);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '\r') SKIP(1);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '@') ADVANCE(19);
      if (lookahead == '}') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(4);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == '}') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == '}') ADVANCE(17);
      END_STATE();
    case 8:
      if (eof) ADVANCE(11);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 9:
      if (eof) ADVANCE(11);
      if (lookahead == '\n') SKIP(10);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '\n') SKIP(10);
      if (lookahead == '\r') SKIP(9);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(15);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '}') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_numeric_index);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_format_spec_token1);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_format_spec_token1);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_format_spec_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 10, .external_lex_state = 1},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 10, .external_lex_state = 1},
  [4] = {.lex_state = 10, .external_lex_state = 1},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10, .external_lex_state = 1},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 10, .external_lex_state = 1},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 10, .external_lex_state = 1},
  [12] = {.lex_state = 10, .external_lex_state = 1},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 10, .external_lex_state = 1},
  [15] = {.lex_state = 10, .external_lex_state = 1},
  [16] = {.lex_state = 10, .external_lex_state = 1},
  [17] = {.lex_state = 10, .external_lex_state = 1},
  [18] = {.lex_state = 10, .external_lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 10, .external_lex_state = 1},
  [21] = {.lex_state = 10, .external_lex_state = 1},
  [22] = {.lex_state = 10, .external_lex_state = 1},
  [23] = {.lex_state = 10, .external_lex_state = 1},
  [24] = {.lex_state = 10, .external_lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 10},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 10},
  [37] = {.lex_state = 10},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_numeric_index] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_literal_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(41),
    [sym__template_content] = STATE(3),
    [sym_property] = STATE(3),
    [sym_go_property] = STATE(3),
    [sym_builtin_property] = STATE(3),
    [aux_sym_template_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(9),
    [sym_literal_text] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_numeric_index,
    ACTIONS(21), 1,
      anon_sym_COLON,
    STATE(6), 1,
      sym_hint_symbol,
    STATE(34), 1,
      sym_format_spec,
    ACTIONS(15), 2,
      anon_sym_AT,
      anon_sym_DOLLAR,
    STATE(27), 2,
      sym__property_name,
      sym_dotted_name,
  [27] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(9), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_literal_text,
    STATE(4), 5,
      sym__template_content,
      sym_property,
      sym_go_property,
      sym_builtin_property,
      aux_sym_template_repeat1,
  [50] = 6,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      anon_sym_LBRACE,
    ACTIONS(32), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(35), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(38), 1,
      sym_literal_text,
    STATE(4), 5,
      sym__template_content,
      sym_property,
      sym_go_property,
      sym_builtin_property,
      aux_sym_template_repeat1,
  [73] = 6,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 1,
      sym_numeric_index,
    STATE(36), 1,
      sym_format_spec,
    STATE(29), 2,
      sym__property_name,
      sym_dotted_name,
  [93] = 6,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    ACTIONS(47), 1,
      sym_numeric_index,
    STATE(35), 1,
      sym_format_spec,
    STATE(28), 2,
      sym__property_name,
      sym_dotted_name,
  [113] = 2,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [123] = 4,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    ACTIONS(55), 1,
      anon_sym_DOT,
    STATE(13), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(57), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COLON,
  [137] = 2,
    ACTIONS(61), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [147] = 4,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(63), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(65), 1,
      sym_numeric_index,
    STATE(40), 2,
      sym__property_name,
      sym_dotted_name,
  [161] = 2,
    ACTIONS(69), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [171] = 2,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(71), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [181] = 4,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(77), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COLON,
  [195] = 2,
    ACTIONS(81), 1,
      anon_sym_LBRACE,
    ACTIONS(79), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [205] = 2,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [215] = 2,
    ACTIONS(89), 1,
      anon_sym_LBRACE,
    ACTIONS(87), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [225] = 2,
    ACTIONS(93), 1,
      anon_sym_LBRACE,
    ACTIONS(91), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [235] = 2,
    ACTIONS(97), 1,
      anon_sym_LBRACE,
    ACTIONS(95), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [245] = 4,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    ACTIONS(101), 1,
      anon_sym_DOT,
    STATE(19), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(104), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COLON,
  [259] = 2,
    ACTIONS(108), 1,
      anon_sym_LBRACE,
    ACTIONS(106), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [269] = 2,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
    ACTIONS(110), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [279] = 2,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(114), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [289] = 2,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [299] = 2,
    ACTIONS(124), 1,
      anon_sym_LBRACE,
    ACTIONS(122), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [309] = 2,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    ACTIONS(104), 3,
      anon_sym_DOT,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COLON,
  [318] = 1,
    ACTIONS(126), 4,
      anon_sym_RBRACE,
      sym_identifier,
      sym_numeric_index,
      anon_sym_COLON,
  [325] = 3,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    STATE(37), 1,
      sym_format_spec,
  [335] = 3,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    STATE(30), 1,
      sym_format_spec,
  [345] = 3,
    ACTIONS(21), 1,
      anon_sym_COLON,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_format_spec,
  [355] = 1,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
  [359] = 1,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
  [363] = 1,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
  [367] = 1,
    ACTIONS(140), 1,
      aux_sym_format_spec_token1,
  [371] = 1,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
  [375] = 1,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
  [379] = 1,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
  [383] = 1,
    ACTIONS(148), 1,
      anon_sym_RBRACE,
  [387] = 1,
    ACTIONS(150), 1,
      anon_sym_DOT,
  [391] = 1,
    ACTIONS(152), 1,
      sym_identifier,
  [395] = 1,
    ACTIONS(154), 1,
      anon_sym_RBRACE_RBRACE,
  [399] = 1,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 73,
  [SMALL_STATE(6)] = 93,
  [SMALL_STATE(7)] = 113,
  [SMALL_STATE(8)] = 123,
  [SMALL_STATE(9)] = 137,
  [SMALL_STATE(10)] = 147,
  [SMALL_STATE(11)] = 161,
  [SMALL_STATE(12)] = 171,
  [SMALL_STATE(13)] = 181,
  [SMALL_STATE(14)] = 195,
  [SMALL_STATE(15)] = 205,
  [SMALL_STATE(16)] = 215,
  [SMALL_STATE(17)] = 225,
  [SMALL_STATE(18)] = 235,
  [SMALL_STATE(19)] = 245,
  [SMALL_STATE(20)] = 259,
  [SMALL_STATE(21)] = 269,
  [SMALL_STATE(22)] = 279,
  [SMALL_STATE(23)] = 289,
  [SMALL_STATE(24)] = 299,
  [SMALL_STATE(25)] = 309,
  [SMALL_STATE(26)] = 318,
  [SMALL_STATE(27)] = 325,
  [SMALL_STATE(28)] = 335,
  [SMALL_STATE(29)] = 345,
  [SMALL_STATE(30)] = 355,
  [SMALL_STATE(31)] = 359,
  [SMALL_STATE(32)] = 363,
  [SMALL_STATE(33)] = 367,
  [SMALL_STATE(34)] = 371,
  [SMALL_STATE(35)] = 375,
  [SMALL_STATE(36)] = 379,
  [SMALL_STATE(37)] = 383,
  [SMALL_STATE(38)] = 387,
  [SMALL_STATE(39)] = 391,
  [SMALL_STATE(40)] = 395,
  [SMALL_STATE(41)] = 399,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 5),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 5),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__property_name, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__property_name, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_property, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtin_property, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 2),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 2),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 3),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotted_name, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_name, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 4),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 4),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_go_property, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_go_property, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_property, 3, 0, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtin_property, 3, 0, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_property, 3, 0, 4),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtin_property, 3, 0, 4),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dotted_name_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_name_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_name_repeat1, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 6),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 6),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 7),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 7),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_go_property, 4, 0, 8),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_go_property, 4, 0, 8),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_property, 4, 0, 7),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtin_property, 4, 0, 7),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 5, 0, 9),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 5, 0, 9),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hint_symbol, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 2, 0, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [156] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_literal_text = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_literal_text] = sym_literal_text,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_literal_text] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_mtlog_external_scanner_create(void);
void tree_sitter_mtlog_external_scanner_destroy(void *);
bool tree_sitter_mtlog_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_mtlog_external_scanner_serialize(void *, char *);
void tree_sitter_mtlog_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mtlog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_mtlog_external_scanner_create,
      tree_sitter_mtlog_external_scanner_destroy,
      tree_sitter_mtlog_external_scanner_scan,
      tree_sitter_mtlog_external_scanner_serialize,
      tree_sitter_mtlog_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "mtlog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
