/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 45
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_LBRACE_LBRACE = 3,
  anon_sym_DOT = 4,
  anon_sym_RBRACE_RBRACE = 5,
  anon_sym_DOLLAR_LBRACE = 6,
  anon_sym_AT = 7,
  anon_sym_DOLLAR = 8,
  sym_identifier = 9,
  sym_numeric_index = 10,
  anon_sym_COLON = 11,
  aux_sym_format_spec_token1 = 12,
  sym_literal_text = 13,
  sym_template = 14,
  sym__template_content = 15,
  sym_property = 16,
  sym_go_property = 17,
  sym_builtin_property = 18,
  sym_hint_symbol = 19,
  sym__property_name = 20,
  sym_dotted_name = 21,
  sym_format_spec = 22,
  aux_sym_template_repeat1 = 23,
  aux_sym_dotted_name_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_DOT] = ".",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [anon_sym_AT] = "@",
  [anon_sym_DOLLAR] = "$",
  [sym_identifier] = "identifier",
  [sym_numeric_index] = "numeric_index",
  [anon_sym_COLON] = ":",
  [aux_sym_format_spec_token1] = "identifier",
  [sym_literal_text] = "literal_text",
  [sym_template] = "template",
  [sym__template_content] = "_template_content",
  [sym_property] = "property",
  [sym_go_property] = "go_property",
  [sym_builtin_property] = "builtin_property",
  [sym_hint_symbol] = "hint_symbol",
  [sym__property_name] = "_property_name",
  [sym_dotted_name] = "dotted_name",
  [sym_format_spec] = "format_spec",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_dotted_name_repeat1] = "dotted_name_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [sym_identifier] = sym_identifier,
  [sym_numeric_index] = sym_numeric_index,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_format_spec_token1] = sym_identifier,
  [sym_literal_text] = sym_literal_text,
  [sym_template] = sym_template,
  [sym__template_content] = sym__template_content,
  [sym_property] = sym_property,
  [sym_go_property] = sym_go_property,
  [sym_builtin_property] = sym_builtin_property,
  [sym_hint_symbol] = sym_hint_symbol,
  [sym__property_name] = sym__property_name,
  [sym_dotted_name] = sym_dotted_name,
  [sym_format_spec] = sym_format_spec,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_dotted_name_repeat1] = aux_sym_dotted_name_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_numeric_index] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_format_spec_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_text] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__template_content] = {
    .visible = false,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_go_property] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin_property] = {
    .visible = true,
    .named = true,
  },
  [sym_hint_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym__property_name] = {
    .visible = false,
    .named = true,
  },
  [sym_dotted_name] = {
    .visible = true,
    .named = true,
  },
  [sym_format_spec] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_name_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_format = 1,
  field_format_string = 2,
  field_hint = 3,
  field_name = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_format] = "format",
  [field_format_string] = "format_string",
  [field_hint] = "hint",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 2},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_format_string, 1},
  [1] =
    {field_hint, 1},
  [2] =
    {field_name, 1},
  [3] =
    {field_format, 1},
  [4] =
    {field_hint, 1},
    {field_name, 2},
  [6] =
    {field_format, 2},
    {field_hint, 1},
  [8] =
    {field_format, 2},
    {field_name, 1},
  [10] =
    {field_name, 2},
  [11] =
    {field_format, 3},
    {field_hint, 1},
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(8);
      if (lookahead == '$') ADVANCE(21);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '@') ADVANCE(19);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '\r') SKIP(1);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '@') ADVANCE(19);
      if (lookahead == '}') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(4);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '\r') SKIP(3);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == '}') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == '}') ADVANCE(17);
      END_STATE();
    case 8:
      if (eof) ADVANCE(11);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 9:
      if (eof) ADVANCE(11);
      if (lookahead == '\n') SKIP(10);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '\n') SKIP(10);
      if (lookahead == '\r') SKIP(9);
      if (lookahead == '$') ADVANCE(6);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '{') ADVANCE(12);
      if (lookahead == '}') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(15);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '}') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '{') ADVANCE(18);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_numeric_index);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_format_spec_token1);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_format_spec_token1);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_format_spec_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 10, .external_lex_state = 1},
  [2] = {.lex_state = 10, .external_lex_state = 1},
  [3] = {.lex_state = 10, .external_lex_state = 1},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 10, .external_lex_state = 1},
  [9] = {.lex_state = 10, .external_lex_state = 1},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 10, .external_lex_state = 1},
  [12] = {.lex_state = 10, .external_lex_state = 1},
  [13] = {.lex_state = 10, .external_lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 10, .external_lex_state = 1},
  [16] = {.lex_state = 10, .external_lex_state = 1},
  [17] = {.lex_state = 10, .external_lex_state = 1},
  [18] = {.lex_state = 10, .external_lex_state = 1},
  [19] = {.lex_state = 10, .external_lex_state = 1},
  [20] = {.lex_state = 10, .external_lex_state = 1},
  [21] = {.lex_state = 10, .external_lex_state = 1},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 10, .external_lex_state = 1},
  [24] = {.lex_state = 10, .external_lex_state = 1},
  [25] = {.lex_state = 10, .external_lex_state = 1},
  [26] = {.lex_state = 10, .external_lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 10},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 10},
  [31] = {.lex_state = 10},
  [32] = {.lex_state = 10},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 10},
  [39] = {.lex_state = 10},
  [40] = {.lex_state = 10},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 10},
  [43] = {.lex_state = 10},
  [44] = {.lex_state = 10},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_numeric_index] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_literal_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(36),
    [sym__template_content] = STATE(3),
    [sym_property] = STATE(3),
    [sym_go_property] = STATE(3),
    [sym_builtin_property] = STATE(3),
    [aux_sym_template_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(9),
    [sym_literal_text] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(18), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(24), 1,
      sym_literal_text,
    STATE(2), 5,
      sym__template_content,
      sym_property,
      sym_go_property,
      sym_builtin_property,
      aux_sym_template_repeat1,
  [23] = 6,
    ACTIONS(5), 1,
      anon_sym_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(9), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym_literal_text,
    STATE(2), 5,
      sym__template_content,
      sym_property,
      sym_go_property,
      sym_builtin_property,
      aux_sym_template_repeat1,
  [46] = 8,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      sym_numeric_index,
    ACTIONS(39), 1,
      anon_sym_COLON,
    STATE(6), 1,
      sym_hint_symbol,
    STATE(43), 1,
      sym_format_spec,
    ACTIONS(33), 2,
      anon_sym_AT,
      anon_sym_DOLLAR,
    STATE(30), 2,
      sym__property_name,
      sym_dotted_name,
  [73] = 6,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_COLON,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 1,
      sym_numeric_index,
    STATE(35), 1,
      sym_format_spec,
    STATE(31), 2,
      sym__property_name,
      sym_dotted_name,
  [93] = 6,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(39), 1,
      anon_sym_COLON,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    ACTIONS(47), 1,
      sym_numeric_index,
    STATE(42), 1,
      sym_format_spec,
    STATE(32), 2,
      sym__property_name,
      sym_dotted_name,
  [113] = 5,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(49), 1,
      anon_sym_DOT,
    ACTIONS(51), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(53), 1,
      sym_numeric_index,
    STATE(41), 2,
      sym__property_name,
      sym_dotted_name,
  [130] = 2,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(55), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [140] = 2,
    ACTIONS(61), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [150] = 4,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(63), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(65), 1,
      sym_numeric_index,
    STATE(37), 2,
      sym__property_name,
      sym_dotted_name,
  [164] = 2,
    ACTIONS(69), 1,
      anon_sym_LBRACE,
    ACTIONS(67), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [174] = 2,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(71), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [184] = 2,
    ACTIONS(77), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [194] = 4,
    ACTIONS(79), 1,
      anon_sym_RBRACE,
    ACTIONS(81), 1,
      anon_sym_DOT,
    STATE(22), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(83), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COLON,
  [208] = 2,
    ACTIONS(87), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [218] = 2,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(89), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [228] = 2,
    ACTIONS(95), 1,
      anon_sym_LBRACE,
    ACTIONS(93), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [238] = 2,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(97), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [248] = 2,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    ACTIONS(101), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [258] = 2,
    ACTIONS(107), 1,
      anon_sym_LBRACE,
    ACTIONS(105), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [268] = 2,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
    ACTIONS(109), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [278] = 4,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    ACTIONS(115), 1,
      anon_sym_DOT,
    STATE(22), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(118), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COLON,
  [292] = 2,
    ACTIONS(122), 1,
      anon_sym_LBRACE,
    ACTIONS(120), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [302] = 2,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(124), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [312] = 2,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(128), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [322] = 2,
    ACTIONS(134), 1,
      anon_sym_LBRACE,
    ACTIONS(132), 4,
      sym_literal_text,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_DOLLAR_LBRACE,
  [332] = 4,
    ACTIONS(81), 1,
      anon_sym_DOT,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(138), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COLON,
  [346] = 1,
    ACTIONS(140), 4,
      anon_sym_RBRACE,
      sym_identifier,
      sym_numeric_index,
      anon_sym_COLON,
  [353] = 2,
    ACTIONS(113), 1,
      anon_sym_RBRACE,
    ACTIONS(118), 3,
      anon_sym_DOT,
      anon_sym_RBRACE_RBRACE,
      anon_sym_COLON,
  [362] = 3,
    ACTIONS(39), 1,
      anon_sym_COLON,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_format_spec,
  [372] = 3,
    ACTIONS(39), 1,
      anon_sym_COLON,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      sym_format_spec,
  [382] = 3,
    ACTIONS(39), 1,
      anon_sym_COLON,
    ACTIONS(146), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      sym_format_spec,
  [392] = 1,
    ACTIONS(148), 1,
      aux_sym_format_spec_token1,
  [396] = 1,
    ACTIONS(150), 1,
      sym_identifier,
  [400] = 1,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
  [404] = 1,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
  [408] = 1,
    ACTIONS(156), 1,
      anon_sym_RBRACE_RBRACE,
  [412] = 1,
    ACTIONS(158), 1,
      anon_sym_RBRACE,
  [416] = 1,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
  [420] = 1,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
  [424] = 1,
    ACTIONS(164), 1,
      anon_sym_RBRACE_RBRACE,
  [428] = 1,
    ACTIONS(166), 1,
      anon_sym_RBRACE,
  [432] = 1,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
  [436] = 1,
    ACTIONS(170), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 46,
  [SMALL_STATE(5)] = 73,
  [SMALL_STATE(6)] = 93,
  [SMALL_STATE(7)] = 113,
  [SMALL_STATE(8)] = 130,
  [SMALL_STATE(9)] = 140,
  [SMALL_STATE(10)] = 150,
  [SMALL_STATE(11)] = 164,
  [SMALL_STATE(12)] = 174,
  [SMALL_STATE(13)] = 184,
  [SMALL_STATE(14)] = 194,
  [SMALL_STATE(15)] = 208,
  [SMALL_STATE(16)] = 218,
  [SMALL_STATE(17)] = 228,
  [SMALL_STATE(18)] = 238,
  [SMALL_STATE(19)] = 248,
  [SMALL_STATE(20)] = 258,
  [SMALL_STATE(21)] = 268,
  [SMALL_STATE(22)] = 278,
  [SMALL_STATE(23)] = 292,
  [SMALL_STATE(24)] = 302,
  [SMALL_STATE(25)] = 312,
  [SMALL_STATE(26)] = 322,
  [SMALL_STATE(27)] = 332,
  [SMALL_STATE(28)] = 346,
  [SMALL_STATE(29)] = 353,
  [SMALL_STATE(30)] = 362,
  [SMALL_STATE(31)] = 372,
  [SMALL_STATE(32)] = 382,
  [SMALL_STATE(33)] = 392,
  [SMALL_STATE(34)] = 396,
  [SMALL_STATE(35)] = 400,
  [SMALL_STATE(36)] = 404,
  [SMALL_STATE(37)] = 408,
  [SMALL_STATE(38)] = 412,
  [SMALL_STATE(39)] = 416,
  [SMALL_STATE(40)] = 420,
  [SMALL_STATE(41)] = 424,
  [SMALL_STATE(42)] = 428,
  [SMALL_STATE(43)] = 432,
  [SMALL_STATE(44)] = 436,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 5),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 5),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 5, 0, 9),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 5, 0, 9),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_go_property, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_go_property, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_property, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtin_property, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotted_name, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_name, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 2),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 4),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 4),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_go_property, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_go_property, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_go_property, 3, 0, 3),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_go_property, 3, 0, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_property, 3, 0, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtin_property, 3, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_property, 3, 0, 4),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtin_property, 3, 0, 4),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dotted_name_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_name_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_name_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 6),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 6),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 7),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 7),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_go_property, 4, 0, 8),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_go_property, 4, 0, 8),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin_property, 4, 0, 7),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtin_property, 4, 0, 7),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__property_name, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__property_name, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hint_symbol, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [154] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_spec, 2, 0, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_literal_text = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_literal_text] = sym_literal_text,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_literal_text] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_mtlog_external_scanner_create(void);
void tree_sitter_mtlog_external_scanner_destroy(void *);
bool tree_sitter_mtlog_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_mtlog_external_scanner_serialize(void *, char *);
void tree_sitter_mtlog_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mtlog(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_mtlog_external_scanner_create,
      tree_sitter_mtlog_external_scanner_destroy,
      tree_sitter_mtlog_external_scanner_scan,
      tree_sitter_mtlog_external_scanner_serialize,
      tree_sitter_mtlog_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "mtlog",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
